/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.MainPanel;

import BUS.KetQuaBUS;
import DTO.KhoaDTO;
import BUS.KhoaBUS;
import DTO.NganhDTO;
import BUS.NganhBUS;
import BUS.NhomBUS;
import BUS.TaiKhoanBUS;
import javax.swing.table.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ASUS
 */
public class SubjectRegistration extends javax.swing.JPanel {

    public JTable getTblNhomMonHoc() {
        return tblNhomMonHoc;
    }

    public void setTblNhomMonHoc(JTable tblNhomMonHoc) {
        this.tblNhomMonHoc = tblNhomMonHoc;
    }

    /**
     * Creates new form SubjectRegistration
     */
    public SubjectRegistration() {
        initComponents();
    }

    public JButton getAdd_btn() {
        return add_btn;
    }

    public void setAdd_btn(JButton add_btn) {
        this.add_btn = add_btn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectRegistration = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        filter_pal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbChuyenBiet = new javax.swing.JComboBox<>();
        cbChuyenBietPhu = new javax.swing.JComboBox<>();
        filterHP_txt = new javax.swing.JTextField();
        filter_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        add_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        javax.swing.JScrollPane jscrollbar = new javax.swing.JScrollPane();
        tblNhomMonHoc = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhomDangKy = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTongTinChi = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();

        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        filter_pal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        filter_pal.setText("Lọc môn học:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Chuyên Biệt:");

        cbChuyenBiet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbChuyenBiet.setMaximumRowCount(100);
        cbChuyenBiet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không", "Môn Chung", "Ngành", "Khoa" }));
        cbChuyenBiet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbChuyenBietItemStateChanged(evt);
            }
        });
        cbChuyenBiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChuyenBietActionPerformed(evt);
            }
        });

        cbChuyenBietPhu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbChuyenBietPhu.setEnabled(false);

        filterHP_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        filterHP_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterHP_txtActionPerformed(evt);
            }
        });

        filter_btn.setBackground(new java.awt.Color(0, 158, 248));
        filter_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        filter_btn.setForeground(new java.awt.Color(255, 255, 255));
        filter_btn.setText("Lọc");
        filter_btn.setContentAreaFilled(false);
        filter_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filter_btn.setOpaque(true);
        filter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filter_pal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(cbChuyenBiet, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbChuyenBietPhu, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(filterHP_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(filter_btn)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filter_pal)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbChuyenBiet)
                    .addComponent(cbChuyenBietPhu))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(filterHP_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filter_btn))
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        add_btn.setBackground(new java.awt.Color(0, 158, 248));
        add_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("Đăng Ký");
        add_btn.setContentAreaFilled(false);
        add_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_btn.setOpaque(true);
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 158, 248));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Môn Học Đề xuất");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_btn))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jscrollbar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblNhomMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên môn", "Nh", "TC", "SL", "CL", "T", "TBD", "ST", "P", "GV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhomMonHoc.setFont(new Font("Segoe UI", 0, 14));
        tblNhomMonHoc.getTableHeader().setFont(new Font("Segoe UI", 0, 16));
        tblNhomMonHoc.setRowHeight(35);
        tblNhomMonHoc.setRowMargin(10);
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.CENTER);
        ((DefaultTableCellRenderer)tblNhomMonHoc.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < tblNhomMonHoc.getColumnCount(); i++)
        {
            tblNhomMonHoc.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);

        }
        tblNhomMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhomMonHocMouseClicked(evt);
            }
        });
        jscrollbar.setViewportView(tblNhomMonHoc);
        if (tblNhomMonHoc.getColumnModel().getColumnCount() > 0) {
            tblNhomMonHoc.getColumnModel().getColumn(0).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(0).setHeaderValue("STT");
            tblNhomMonHoc.getColumnModel().getColumn(1).setMaxWidth(60);
            tblNhomMonHoc.getColumnModel().getColumn(1).setHeaderValue("Mã");
            tblNhomMonHoc.getColumnModel().getColumn(2).setHeaderValue("Tên môn");
            tblNhomMonHoc.getColumnModel().getColumn(3).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(3).setHeaderValue("Nh");
            tblNhomMonHoc.getColumnModel().getColumn(4).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(4).setHeaderValue("TC");
            tblNhomMonHoc.getColumnModel().getColumn(5).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(5).setHeaderValue("SL");
            tblNhomMonHoc.getColumnModel().getColumn(6).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(6).setHeaderValue("CL");
            tblNhomMonHoc.getColumnModel().getColumn(7).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(7).setHeaderValue("T");
            tblNhomMonHoc.getColumnModel().getColumn(8).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(8).setHeaderValue("TBD");
            tblNhomMonHoc.getColumnModel().getColumn(9).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(9).setHeaderValue("ST");
            tblNhomMonHoc.getColumnModel().getColumn(10).setMaxWidth(50);
            tblNhomMonHoc.getColumnModel().getColumn(10).setHeaderValue("P");
            tblNhomMonHoc.getColumnModel().getColumn(11).setMinWidth(150);
            tblNhomMonHoc.getColumnModel().getColumn(11).setMaxWidth(200);
            tblNhomMonHoc.getColumnModel().getColumn(11).setHeaderValue("GV");
        }

        tblNhomDangKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên Môn", "NH", "TC", "% GK", "% CK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhomDangKy.setFont(new Font("Segoe UI", 0, 14));
        tblNhomDangKy.getTableHeader().setFont(new Font("Segoe UI", 0, 16));
        tblNhomDangKy.setRowHeight(35);
        tblNhomDangKy.setRowMargin(10);
        DefaultTableCellRenderer leftRenderer2 = new DefaultTableCellRenderer();
        leftRenderer2.setHorizontalAlignment(JLabel.CENTER);
        ((DefaultTableCellRenderer)tblNhomDangKy.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < tblNhomDangKy.getColumnCount(); i++)
        {

            tblNhomDangKy.getColumnModel().getColumn(i).setCellRenderer(leftRenderer2);

        }
        jScrollPane2.setViewportView(tblNhomDangKy);
        if (tblNhomDangKy.getColumnModel().getColumnCount() > 0) {
            tblNhomDangKy.getColumnModel().getColumn(0).setMaxWidth(60);
            tblNhomDangKy.getColumnModel().getColumn(1).setMaxWidth(80);
            tblNhomDangKy.getColumnModel().getColumn(3).setMaxWidth(60);
            tblNhomDangKy.getColumnModel().getColumn(4).setMaxWidth(60);
            tblNhomDangKy.getColumnModel().getColumn(5).setMaxWidth(60);
            tblNhomDangKy.getColumnModel().getColumn(6).setMaxWidth(60);
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Môn học đã đăng kí:");

        lblTongTinChi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTongTinChi.setText("Tổng số tín chỉ:");

        btnXoa.setBackground(new java.awt.Color(0, 158, 248));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setContentAreaFilled(false);
        btnXoa.setOpaque(true);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTongTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTongTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscrollbar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jscrollbar, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout subjectRegistrationLayout = new javax.swing.GroupLayout(subjectRegistration);
        subjectRegistration.setLayout(subjectRegistrationLayout);
        subjectRegistrationLayout.setHorizontalGroup(
            subjectRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );
        subjectRegistrationLayout.setVerticalGroup(
            subjectRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(subjectRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1043, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(subjectRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnXoa() {
        return btnXoa;
    }

    public void setBtnXoa(JButton btnXoa) {
        this.btnXoa = btnXoa;
    }

    public JLabel getLblTongTinChi() {
        return lblTongTinChi;
    }

    public void setLblTongTinChi(JLabel lblTongTinChi) {
        this.lblTongTinChi = lblTongTinChi;
    }


    private void filter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_btnActionPerformed
        String hocPhan = filterHP_txt.getText();
        if (hocPhan.equals("") && cbChuyenBiet.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Nhập môn học!", "Bổ sung", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String chuyenBiet = cbChuyenBiet.getSelectedItem() + "";
        String chuyenBietPhu = cbChuyenBietPhu.getSelectedItem() + "";
        if (chuyenBiet.equals("Ngành") && chuyenBietPhu.equals("Chọn Ngành")
                || chuyenBiet.equals("Khoa") && chuyenBietPhu.equals("Chọn Khoa")) {
            JOptionPane.showMessageDialog(null, "Chọn giá trị chuyên biệt!", "Bổ sung", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (chuyenBietPhu != null) {
            chuyenBietPhu = chuyenBietPhu.split("-")[0];
        }
        NhomBUS.filterGroup(hocPhan, chuyenBiet, chuyenBietPhu, tblNhomMonHoc);


    }//GEN-LAST:event_filter_btnActionPerformed

    private void filterHP_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterHP_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterHP_txtActionPerformed

    private void cbChuyenBietItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbChuyenBietItemStateChanged
        //evt.getStateChange == 1 when Selected
        if (evt.getStateChange() == 1) {
            switch (cbChuyenBiet.getSelectedItem() + "") {
                case "Không" -> {
                    cbChuyenBietPhu.removeAllItems();
                    cbChuyenBietPhu.setEnabled(false);
                }
                case "Môn Chung" -> {
                    cbChuyenBietPhu.removeAllItems();
                    cbChuyenBietPhu.setEnabled(false);
                }
                case "Ngành" -> {
                    cbChuyenBietPhu.removeAllItems();
                    cbChuyenBietPhu.setEnabled(true);
                    cbChuyenBietPhu.addItem("Chọn Ngành");
                    for (NganhDTO nganh : NganhBUS.getDsNganh()) {
                        cbChuyenBietPhu.addItem(nganh.getMaNganh() + "-" + nganh.getTenNganh());
                    }
                }
                case "Khoa" -> {
                    cbChuyenBietPhu.removeAllItems();
                    cbChuyenBietPhu.setEnabled(true);
                    cbChuyenBietPhu.addItem("Chọn Khoa");
                    for (KhoaDTO khoa : KhoaBUS.getDsKhoa()) {
                        cbChuyenBietPhu.addItem(khoa.getMaKhoa() + "-" + khoa.getTenKhoa());
                    }
                }
            }
        }
    }//GEN-LAST:event_cbChuyenBietItemStateChanged

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        int i = tblNhomMonHoc.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn nhóm môn học!", "Đăng ký môn học", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String maHP = tblNhomMonHoc.getValueAt(i, 1) + "";
        int soNhom = Integer.parseInt(tblNhomMonHoc.getValueAt(i, 3) + "");
        if (KetQuaBUS.subjectRegistration(maHP, soNhom)) {
            JOptionPane.showMessageDialog(null, "Đang ký thành công!", "Đăng ký môn học", JOptionPane.INFORMATION_MESSAGE);
            reloadSubjectRegistration();
        }
    }//GEN-LAST:event_add_btnActionPerformed
    public void reloadSubjectRegistration() {
        NhomBUS.showGroupSuggestions(tblNhomMonHoc);
        NhomBUS.showGroupRegistration(tblNhomDangKy, lblTongTinChi);
        filterHP_txt.setText("");
        cbChuyenBiet.setSelectedIndex(0);
    }

    public JTable getTblNhomDangKy() {
        return tblNhomDangKy;
    }

    public void setTblNhomDangKy(JTable tblNhomDangKy) {
        this.tblNhomDangKy = tblNhomDangKy;
    }

    private void tblNhomMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhomMonHocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblNhomMonHocMouseClicked

    private void cbChuyenBietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChuyenBietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChuyenBietActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NhomBUS.showGroupSuggestions(tblNhomMonHoc);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int i = tblNhomDangKy.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn nhóm đăng ký!", "Đăng ký môn học", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String maHP = tblNhomDangKy.getValueAt(i, 1) + "";
        int soNhom = Integer.parseInt(tblNhomDangKy.getValueAt(i, 3) + "");
        KetQuaBUS.deleteSubjectRegister(maHP, soNhom);
        reloadSubjectRegistration();
    }//GEN-LAST:event_btnXoaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbChuyenBiet;
    private javax.swing.JComboBox<String> cbChuyenBietPhu;
    private javax.swing.JTextField filterHP_txt;
    private javax.swing.JButton filter_btn;
    private javax.swing.JLabel filter_pal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTongTinChi;
    private javax.swing.JPanel subjectRegistration;
    private javax.swing.JTable tblNhomDangKy;
    private javax.swing.JTable tblNhomMonHoc;
    // End of variables declaration//GEN-END:variables
}
