/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.mainPanel;

import backend.Khoa.Khoa;
import backend.Khoa.KhoaBUS;
import backend.Nganh.Nganh;
import backend.Nganh.NganhBUS;
import backend.Nhom.NhomBUS;
import javax.swing.table.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ASUS
 */
public class SubjectRegistration extends javax.swing.JPanel {

    public JTable getTblNhomMonHoc() {
        return tblNhomMonHoc;
    }

    public void setTblNhomMonHoc(JTable tblNhomMonHoc) {
        this.tblNhomMonHoc = tblNhomMonHoc;
    }

    /**
     * Creates new form SubjectRegistration
     */
    public SubjectRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectRegistration = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        filter_pal = new javax.swing.JLabel();
        filterHP_txt = new javax.swing.JTextField();
        filter_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbChuyenBietPhu = new javax.swing.JComboBox<>();
        cbChuyenBiet = new javax.swing.JComboBox<>();
        jscrollbar = new javax.swing.JScrollPane();
        tblNhomMonHoc = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        filter_pal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        filter_pal.setText("Lọc môn học:");

        filterHP_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        filterHP_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterHP_txtActionPerformed(evt);
            }
        });

        filter_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        filter_btn.setText("Lọc");
        filter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_btnActionPerformed(evt);
            }
        });

        add_btn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add_btn.setText("Thêm");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Chuyên Biệt:");

        cbChuyenBietPhu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbChuyenBietPhu.setEnabled(false);

        cbChuyenBiet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbChuyenBiet.setMaximumRowCount(100);
        cbChuyenBiet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không", "Môn Chung", "Ngành", "Khoa" }));
        cbChuyenBiet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbChuyenBietItemStateChanged(evt);
            }
        });
        cbChuyenBiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChuyenBietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter_pal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbChuyenBiet, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbChuyenBietPhu, 0, 236, Short.MAX_VALUE))
                    .addComponent(filterHP_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filter_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(add_btn)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filterHP_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(filter_btn))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filter_pal)
                        .addComponent(add_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbChuyenBietPhu)
                    .addComponent(cbChuyenBiet))
                .addGap(14, 14, 14))
        );

        tblNhomMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên môn", "Nh", "TC", "SL", "CL", "T", "TBD", "ST", "P", "GV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhomMonHoc.setFont(new Font("Segoe UI", 0, 14));
        tblNhomMonHoc.getTableHeader().setFont(new Font("Segoe UI", 0, 16));
        tblNhomMonHoc.setRowHeight(35);
        tblNhomMonHoc.setRowMargin(10);
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.CENTER);
        ((DefaultTableCellRenderer)tblNhomMonHoc.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < tblNhomMonHoc.getColumnCount(); i++)
        {

            if(i != 1){
                tblNhomMonHoc.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
            }else{
                continue;
            }
        }
        tblNhomMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhomMonHocMouseClicked(evt);
            }
        });
        jscrollbar.setViewportView(tblNhomMonHoc);
        if (tblNhomMonHoc.getColumnModel().getColumnCount() > 0) {
            tblNhomMonHoc.getColumnModel().getColumn(0).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(1).setMaxWidth(60);
            tblNhomMonHoc.getColumnModel().getColumn(3).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(4).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(5).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(6).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(7).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(8).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(9).setMaxWidth(40);
            tblNhomMonHoc.getColumnModel().getColumn(10).setMaxWidth(50);
            tblNhomMonHoc.getColumnModel().getColumn(11).setMinWidth(150);
            tblNhomMonHoc.getColumnModel().getColumn(11).setMaxWidth(200);
        }

        jTable2.getTableHeader().setFont(new Font("Segoe UI", 0, 16));
        leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.CENTER);
        ((DefaultTableCellRenderer)jTable2.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < jTable2.getColumnCount(); i++)
        {

            if(i != 2){
                jTable2.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
            }else{
                continue;
            }
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jscrollbar))
                .addGap(18, 18, 18))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscrollbar, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout subjectRegistrationLayout = new javax.swing.GroupLayout(subjectRegistration);
        subjectRegistration.setLayout(subjectRegistrationLayout);
        subjectRegistrationLayout.setHorizontalGroup(
            subjectRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        subjectRegistrationLayout.setVerticalGroup(
            subjectRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(subjectRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(subjectRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_btnActionPerformed
        String hocPhan = filterHP_txt.getText();
        NhomBUS.filterGroup(hocPhan, tblNhomMonHoc);
    }//GEN-LAST:event_filter_btnActionPerformed

    private void filterHP_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterHP_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterHP_txtActionPerformed

    private void cbChuyenBietItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbChuyenBietItemStateChanged
        //evt.getStateChange == 1 when Selected
        if (evt.getStateChange() == 1) {
            switch (cbChuyenBiet.getSelectedIndex()) {
                case 0 -> { //Không
                    cbChuyenBietPhu.removeAllItems();
                    cbChuyenBietPhu.setEnabled(false);
                }
                case 1 -> {//Môn chung
                    cbChuyenBietPhu.removeAllItems();
                    cbChuyenBietPhu.setEnabled(false);
                }
                case 2 -> {//nganh
                    cbChuyenBietPhu.removeAllItems();
                    cbChuyenBietPhu.setEnabled(true);
                    cbChuyenBietPhu.addItem("Chọn Ngành");
                    for (Nganh nganh : NganhBUS.getDsNganh()) {
                        cbChuyenBietPhu.addItem(nganh.getMaNganh() + "-" + nganh.getTenNganh());
                    }

                }
                case 3 -> {//khoa
                    cbChuyenBietPhu.removeAllItems();
                    cbChuyenBietPhu.setEnabled(true);
                    cbChuyenBietPhu.addItem("Chọn Khoa");
                    for (Khoa khoa : KhoaBUS.getDsKhoa()) {
                        cbChuyenBietPhu.addItem(khoa.getMaKhoa() + "-" + khoa.getTenKhoa());
                    }
                }
            }
        }
    }//GEN-LAST:event_cbChuyenBietItemStateChanged

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed

    }//GEN-LAST:event_add_btnActionPerformed

    private void tblNhomMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhomMonHocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblNhomMonHocMouseClicked

    private void cbChuyenBietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChuyenBietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChuyenBietActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JComboBox<String> cbChuyenBiet;
    private javax.swing.JComboBox<String> cbChuyenBietPhu;
    private javax.swing.JTextField filterHP_txt;
    private javax.swing.JButton filter_btn;
    private javax.swing.JLabel filter_pal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JScrollPane jscrollbar;
    private javax.swing.JPanel subjectRegistration;
    private javax.swing.JTable tblNhomMonHoc;
    // End of variables declaration//GEN-END:variables
}
